version: "2.3"
services:
  # ubook this spins up a server that serves the html/js/css for the e2e tests
  ubook-server:
    command: yarn ubook:serve
    build: .
    ports:
      - "51372:51372"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -H "Accept: text/html" -f http://ubook-server:51372 || exit 1',
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - COMPOSE_HTTP_TIMEOUT

  # tests if the e2e-server is ready to serve traffic
  ubook-server-healthy:
    build: .
    links:
      - ubook-server
    depends_on:
      ubook-server:
        condition: service_healthy

  # running the snapshot tests in ci
  ubook-test:
    build: .
    security_opt:
      - seccomp:chrome.json
    links:
      - ubook-server
    volumes:
      - ./artifacts:/ubook/artifacts
    depends_on:
      - ubook-server-healthy
    environment:
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_REPO
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET_NAME
