steps:
  # - name: ":docker: :package: snapshot"
  #   plugins:
  #     "docker-compose#v3.0.3":
  #       build:
  #         - ubook-test
  #         - ubook-server
  #         - ubook-server-healthy
  #   agents:
  #     queue: builders
  # - wait
  # Wait until all images are built.
  # This way we can download the built image from a registry instead of building each for each test task.
  # All of the commands after the wait are run in parallel.
  - name: snapshot
    command: yarn ubook:snapshot:ci
    timeout_in_minutes: 30
    soft_fail:
      - exit_status: "*"
    artifact_paths:
      - "artifacts/**/*.png"
    # plugins:
    #   "docker-compose#v3.0.3":
    #     run: ubook-test
    #     pull:
    #       - ubook-server
    #       - ubook-server-healthy
    agents:
      queue: workers
  - block: ":book: ubook snapshots mismatch"
    prompt: "uBook snapshosts don't match the master branch. Please check the previous step and artifacts. Is it ok to proceed and update master?"
    depends_on: "snapshot"
    if: build.message === "ahahah"
