steps:
  - name: ":storybook: ubook-snapshots"
    command: ./ubook_snapshot.sh
    timeout_in_minutes: 30
    soft_fail:
      - exit_status: 1
    artifact_paths:
      - "artifacts/**/*.png"
    plugins:
      "docker-compose#v3.0.3":
        volumes:
          - ${BUILDKITE_AGENT_BINARY_PATH:-/usr/bin/buildkite-agent}:/usr/bin/buildkite-agent
        environment:
          - BUILDKITE_JOB_ID
          - BUILDKITE_BUILD_ID
          - BUILDKITE_AGENT_ACCESS_TOKEN
    agents:
      queue: workers
