steps:
  - block: ":incoming_envelope: update-snapshots"
    prompt: "uBook snapshosts don't match the master branch. Is it ok to proceed and update master?"
  - name: ":docker: :package: snapshot"
    plugins:
      "docker-compose#v3.0.3":
        build:
          - ubook-test
          - ubook-server
          - ubook-server-healthy
    agents:
      queue: builders
  - wait
  # Wait until all images are built.
  # This way we can download the built image from a registry instead of building each for each test task.
  # All of the commands after the wait are run in parallel.
  - name: snapshot
    command: yarn ubook:snapshot:ci
    artifact_paths:
      - "artifacts/**/*.png"
    plugins:
      "docker-compose#v3.0.3":
        run: ubook-test
        pull:
          - ubook-server
          - ubook-server-healthy
    agents:
      queue: workers
