steps:
  - block: ":storybook: uBook snapshots mismatch"
    prompt: "uBook snapshosts don't match the master branch. Please check the previous step and its artifacts.\n\nIs it ok to proceed and update the master snapshots?"
  - wait
  - label: ":storybook: uBook snapshots will be updated"
    command:
    agents:
      queue: workers
